name: Reusable component workflow

on:
  workflow_call:
    inputs:
      build-tag:
        type: string
        required: true
      target-platform:
        type: string
        required: true
      target-archs:
        type: string
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      BUILD_TAG: ${{ inputs.build-tag }}
      TARGET_PLATFORM: ${{ inputs.target-platform }}
      TARGET_ARCHS: ${{ inputs.target-archs }}
      COMPONENT: ffmpeg
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: docker/setup-qemu-action@v2
        name: Setup QEMU
      - uses: docker/setup-buildx-action@v2
        name: Setup Docker Buildx
      - uses: docker/login-action@v2
        name: Login to GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        name: Build Docker image
        with:
          context: platforms/${{ env.TARGET_PLATFORM }}/${{ env.COMPONENT }}
          platforms: ${{ env.TARGET_ARCHS }}
          build-args: |
            IMAGE_PREFIX=ghcr.io/${{ github.repository }}/${{ env.TARGET_PLATFORM }}/
            TAG=${{ env.BUILD_TAG }}
            FFMPEG_VERSION_SUFFIX=github.com/${{ github.repository }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.TARGET_PLATFORM }}/${{ env.COMPONENT }}:${{ env.BUILD_TAG }}
          cache-from: type=gha,scope=${{ env.TARGET_PLATFORM }}-${{ env.COMPONENT }}-${{ env.BUILD_TAG }}
          cache-to: type=gha,mode=max,scope=${{ env.TARGET_PLATFORM }}-${{ env.COMPONENT }}-${{ env.BUILD_TAG }}
